
let prefix='/src/asset'

let emoji = {
  faceList: [{ type: 'emoji', label: '😀' }, { label: `${prefix}/emoji/smile.webp` }],
  emojiList: [
    [
      { type: 'emoji', label: '😀' },
      { type: 'emoji', label: '😂' },
      { type: 'emoji', label: '😮' },
      { type: 'emoji', label: '😍' },
      { type: 'emoji', label: '😘' },
      { type: 'emoji', label: '😚' },
      { type: 'emoji', label: '🤩' },
      { type: 'emoji', label: '🥰' },
      { type: 'emoji', label: '😋' },
      { type: 'emoji', label: '😛' },
      { type: 'emoji', label: '😜' },
      { type: 'emoji', label: '😝' },
      { type: 'emoji', label: '🤑' },
      { type: 'emoji', label: '🤪' },
      { type: 'emoji', label: '🤔' },
      { type: 'emoji', label: '🤗' },
      { type: 'emoji', label: '🤫' },
      { type: 'emoji', label: '🤭' },
      { type: 'emoji', label: '😏' },
      { type: 'emoji', label: '🙄' },
      { type: 'emoji', label: '😐' },
      { type: 'emoji', label: '😑' },
      { type: 'emoji', label: '😒' },
      { type: 'emoji', label: '😌' },
      { type: 'emoji', label: '😴' },
      { type: 'emoji', label: '😵' },
      { type: 'emoji', label: '😷' },
      { type: 'emoji', label: '🤕' },
      { type: 'emoji', label: '😷' },
      { type: 'emoji', label: '🤢' },
      { type: 'emoji', label: '🤠' },
      { type: 'emoji', label: '😎' },
      { type: 'emoji', label: '😱' },
      { type: 'emoji', label: '🥺' },
      { type: 'emoji', label: '😡' },
    ],
    [
      { label: '[口罩]', value: `${prefix}/emoji/kouzhao.webp` },
      { label: '[狗头]', value: `${prefix}/emoji/goutou.webp` },
      { label: '[微笑]', value: `${prefix}/emoji/smile.webp` },
      { label: '[微笑2]', value: `${prefix}/emoji/smile2.webp` },
      { label: '[OK]', value: `${prefix}/emoji/ok.webp` },
      { label: '[星星眼]', value: `${prefix}/emoji/star.webp` },
      { label: '[辣眼睛]', value: `${prefix}/emoji/layanjing.webp` },
      { label: '[吃瓜]', value: `${prefix}/emoji/huaji.webp` },
      { label: '[滑稽]', value: `${prefix}/emoji/chigua.webp` },
      { label: '[呲牙]', value: `${prefix}/emoji/teeth.webp` },
      { label: '[打call]', value: `${prefix}/emoji/dacall.webp` },
      { label: '[喝酒]', value: `${prefix}/emoji/hejiu.webp` },
      { label: '[乖]', value: `${prefix}/emoji/guai.webp` },
      { label: '[吐舌]', value: `${prefix}/emoji/tushe.webp` },
      { label: '[汗]', value: `${prefix}/emoji/han.webp` },
      { label: '[大哭2]', value: `${prefix}/emoji/daku.webp` },
      { label: '[超赞]', value: `${prefix}/emoji/chaozan.webp` },
      { label: '[超开心]', value: `${prefix}/emoji/chaokaixin.webp` },
      { label: '[委屈]', value: `${prefix}/emoji/weiqu.webp` },
      { label: '[困狗]', value: `${prefix}/emoji/kungou.webp` },
      { label: '[藏狐]', value: `${prefix}/emoji/zanghu.webp` },
      { label: '[脸红]', value: `${prefix}/emoji/lianhong.webp` },
      { label: '[脱单doge]', value: `${prefix}/emoji/doge.webp` },
      { label: '[给心心]', value: `${prefix}/emoji/heart.webp` },
      { label: '[笑]', value: `${prefix}/emoji/dx.webp` },
      { label: '[哦呼]', value: `${prefix}/emoji/oh.webp` },
      { label: '[嫌弃]', value: `${prefix}/emoji/xq.webp` },
      { label: '[喜欢]', value: `${prefix}/emoji/like.webp` },
      { label: '[酸了]', value: `${prefix}/emoji/sl.webp` },
      { label: '[大哭]', value: `${prefix}/emoji/dq.webp` },
      { label: '[害羞]', value: `${prefix}/emoji/hx.webp` },
      { label: '[无语]', value: `${prefix}/emoji/wy.webp` },
      { label: '[疑惑]', value: `${prefix}/emoji/yh.webp` },
      { label: '[调皮]', value: `${prefix}/emoji/tiaopi.webp` },
      { label: '[笑哭]', value: `${prefix}/emoji/xiaoku.webp` },
      { label: '[奸笑]', value: `${prefix}/emoji/jianxiao.webp` },
      { label: '[偷笑]', value: `${prefix}/emoji/touxiao.webp` },
      { label: '[阴险]', value: `${prefix}/emoji/yinxian.webp` },
      { label: '[捂脸]', value: `${prefix}/emoji/wulian.webp` },
      { label: '[无语]', value: `${prefix}/emoji/wy.webp` },
      { label: '[妙啊]', value: `${prefix}/emoji/miaoa.webp` },
      { label: '[鼓掌]', value: `${prefix}/emoji/guzhang.webp` },
      { label: '[尴尬]', value: `${prefix}/emoji/ganga.webp` },
      { label: '[冷]', value: `${prefix}/emoji/cold.webp` },
      { label: '[灵魂出窍]', value: `${prefix}/emoji/linghunchuqiao.webp` },
      { label: '[傲娇]', value: `${prefix}/emoji/aojiao.webp` },
      { label: '[疼]', value: `${prefix}/emoji/teng.webp` },
      { label: '[吓]', value: `${prefix}/emoji/xia.webp` },
      { label: '[生病]', value: `${prefix}/emoji/shengbing.webp` },
      { label: '[吐]', value: `${prefix}/emoji/tu.webp` },
      { label: '[嘘声]', value: `${prefix}/emoji/xusheng.webp` },
      { label: '[捂眼]', value: `${prefix}/emoji/wuyan.webp` },
      { label: '[思考]', value: `${prefix}/emoji/sikao.webp` },
      { label: '[再见]', value: `${prefix}/emoji/zaijian.webp` },
      { label: '[翻白眼]', value: `${prefix}/emoji/fanbaiyan.webp` },
      { label: '[哈欠]', value: `${prefix}/emoji/haqian.webp` },
      { label: '[奋斗]', value: `${prefix}/emoji/fengdou.webp` },
      { label: '[墨镜]', value: `${prefix}/emoji/mojing.webp` },
      { label: '[撇嘴]', value: `${prefix}/emoji/piezui.webp` },
      { label: '[难过]', value: `${prefix}/emoji/nanguo.webp` },
      { label: '[抓狂]', value: `${prefix}/emoji/zhuakuang.webp` },
      { label: '[生气]', value: `${prefix}/emoji/shengqi.webp` },
      { label: '[爱心]', value: `${prefix}/emoji/aixin.webp` },
      { label: '[胜利]', value: `${prefix}/emoji/shengli.webp` },
      { label: '[抱拳]', value: `${prefix}/emoji/baoquan.webp` },
      { label: '[保佑]', value: `${prefix}/emoji/baoyou.webp` },
      { label: '[支持]', value: `${prefix}/emoji/zhichi.webp` },
    ]
  ],
  activeIndex: 1
}

if (emoji) {
  let obj = emoji.emojiList.reduce((acc, cur) => {
    let arr = cur.filter(e => e.type != 'emoji')
    arr.forEach(e => {
      acc[e.label] = e.value
    })
    return acc
  }, {})
  emoji.allEmoji = obj
}

export default {
  ...emoji
}